# Welcome to Jekyll!
title: Open Source Software Soft-Serve, now in GitHub flavour
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:

# theme: oss-soft-serve

permalink: /docs/:title

exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed

# Basic product information.
name: OSS Soft Serve
logo: #/images/path/to/logo

# Version and license
version: 1.0  # http://semver.org/
license: MIT # https://opensource.org/licenses/MIT

# Where is your product available?
# If you need a source not listed, add below. OSS Soft-Serve will loop.
main_repo:
  name: Github
  url: https://github.com/hougasian/oss-soft-serve
  fork: true # assumes Github if true; adds upper corner badge
  color: olive # fork badge color: Red Orange Yellow Olive Green Teal Blue Violet Purple Pink Brown Grey Black

# Any secondary distribution sources?
repos:
  gem:
  nuget:

# Product CTAs (Calls to Action).
cta:
  main: "A Jekyll template for that thing you made!"
  secondary: "Build it, document it, promote it, the <span>soft-serve</span> way."
