# Welcome to Jekyll!
title: Open Source Software Soft-Serve, now in GitHub flavour
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:

# theme: oss-soft-serve

permalink: /docs/:title
exclude:
  - Gemfile
  - Gemfile.lock

gems:
  - jekyll-feed

sass:
  style: compressed
